---
- name: Prepare nodes
  gather_facts: true
  hosts: cluster
  become: true
  tags:
    - all
    - prepare
  tasks:
    - import_tasks: tasks/ensure_packages.yml

- name: Update k3s master nodes
  hosts: masters
  gather_facts: false
  serial: 1
  become: true
  tags:
    - all
    - update-k3s
    - update-k3s-masters
  vars:
    unit_name: k3s
    reboot_desired: false
  tasks:
    - import_tasks: tasks/update_system.yml

    - include_tasks: tasks/obtain_install_script.yml

    - name: Get node public IP
      register: public_ip_lookup
      community.general.ipify_facts:

    - name: Execute k3s install script
      vars:
        default_if_ipv4: '{{ ansible_facts[default_if_name].ipv4.address }}'
        public_inet_ipv4: '{{ public_ip_lookup.ansible_facts.ipify_public_ip }}'
        write_kubeconfig_mode: '0644'
      ansible.builtin.command:
        argv:
          - '{{ install_script.path }}'
          - server
          - --flannel-iface={{ default_if_name }}
          - --node-external-ip={{ public_inet_ipv4 }}
          - --node-ip={{ default_if_ipv4 }}
          - --advertise-address={{ default_if_ipv4 }}
          - --write-kubeconfig-mode={{ write_kubeconfig_mode }}

    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      register: reboot_required_file
      ansible.builtin.stat: path=/var/run/reboot-required get_md5=no

    - include_tasks: tasks/clean_reboot.yml
      when: reboot_required_file.stat.exists or reboot_desired
      vars:
        node_drain_delegate_host: '{{ inventory_hostname }}'

- name: Update k3s workers nodes
  hosts: workers
  gather_facts: false
  serial: 1
  become: true
  vars:
    unit_name: k3s-agent
    reboot_desired: false
    first_master_node_name: '{{ groups.masters | first }}'
  tags:
    - all
    - update-k3s
    - update-k3s-workers
  tasks:
    - import_tasks: tasks/update_system.yml

    - include_tasks: tasks/obtain_install_script.yml

    - name: Get node public IP
      register: public_ip_lookup
      community.general.ipify_facts:

    - name: Read first master token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/token
      delegate_to: '{{ first_master_node_name }}'
      delegate_facts: false
      register: first_master_token_slurp

    - name: Execute k3s install script
      vars:
        default_if_ipv4: '{{ ansible_facts[default_if_name].ipv4.address }}'
        public_inet_ipv4: '{{ public_ip_lookup.ansible_facts.ipify_public_ip }}'

        first_master_default_if_name: '{{ hostvars[first_master_node_name].default_if_name }}'
        first_master_server_ip: '{{ hostvars[first_master_node_name].ansible_facts[first_master_default_if_name].ipv4.address }}'
        first_master_token: "{{ first_master_token_slurp['content'] | b64decode | trim }}"
      ansible.builtin.command:
        argv:
          - '{{ install_script.path }}'
          - agent
          - --server=https://{{ first_master_server_ip }}:6443
          - --token={{ first_master_token | quote }}
          - --flannel-iface={{ default_if_name }}
          - --node-external-ip={{ public_inet_ipv4 }}
          - --node-ip={{ default_if_ipv4 }}

    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      register: reboot_required_file
      ansible.builtin.stat: path=/var/run/reboot-required get_md5=no

    - include_tasks: tasks/clean_reboot.yml
      when: reboot_required_file.stat.exists or reboot_desired
      vars:
        node_drain_delegate_host: '{{ first_master_node_name }}'
