- name: Prepare nodes
  gather_facts: true
  hosts: cluster
  become: true
  tags:
    - all
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        pkg:
          - policycoreutils

- name: Update k3s master nodes
  hosts: masters
  gather_facts: false
  serial: 1
  become: true
  tags:
    - all
    - update-k3s
    - update-k3s-masters
  vars:
    reboot_desired: false
  tasks:
    - name: Update apt-get repo and cache
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      ansible.builtin.apt: upgrade=dist force_apt_get=yes

    - name: Get node public IP
      register: public_ip_lookup
      community.general.ipify_facts:

    - name: Create temporary file for k3s install script
      ansible.builtin.tempfile:
        prefix: k3s-install-script-
        suffix: .sh
      register: install_script

    - name: Set permissions for k3s install script
      ansible.builtin.file:
        path: '{{ install_script.path }}'
        mode: '0740'

    - name: Download k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: '{{ install_script.path }}'

    - name: Execute k3s install script
      vars:
        default_if_ipv4: '{{ ansible_facts[default_if_name].ipv4.address }}'
        public_inet_ipv4: '{{ public_ip_lookup.ansible_facts.ipify_public_ip }}'
        write_kubeconfig_mode: '0644'
      ansible.builtin.command:
        argv:
          - '{{ install_script.path }}'
          - --flannel-iface={{ default_if_name }}
          - --node-external-ip={{ public_inet_ipv4 }}
          - --node-ip={{ default_if_ipv4 }}
          - --advertise-address={{ default_if_ipv4 }}
          - --write-kubeconfig-mode={{ write_kubeconfig_mode }}

    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      register: reboot_required_file
      ansible.builtin.stat: path=/var/run/reboot-required get_md5=no

    - name: Drain current node
      ansible.builtin.command: /usr/local/bin/kubectl drain {{ inventory_hostname }} --force
      when: reboot_required_file.stat.exists or reboot_desired
      failed_when: false

    - name: Stop k3s service
      ansible.builtin.systemd:
        name: k3s
        state: stopped
        enabled: false
      when: reboot_required_file.stat.exists or reboot_desired

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: 'Reboot initiated by Ansible due to kernel updates'
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists or reboot_desired

    - name: Execute k3s-killall
      ansible.builtin.command: /usr/local/bin/k3s-killall.sh
      when: reboot_required_file.stat.exists or reboot_desired

    - name: Start k3s service
      ansible.builtin.systemd:
        name: k3s
        state: started
        enabled: true
      when: reboot_required_file.stat.exists or reboot_desired

    - name: Uncordon current node
      until: uncordon.rc == 0
      register: uncordon
      delay: 5
      ansible.builtin.command: /usr/local/bin/kubectl uncordon {{ inventory_hostname }}
      when: reboot_required_file.stat.exists or reboot_desired

- name: Update k3s workers nodes
  hosts: workers
  gather_facts: false
  serial: 1
  become: true
  vars:
    reboot_desired: false
    first_master_node_name: '{{ groups.masters | first }}'
  tags:
    - all
    - update-k3s
    - update-k3s-workers
  tasks:
    - name: Update apt-get repo and cache
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      ansible.builtin.apt: upgrade=dist force_apt_get=yes

    - name: Get node public IP
      register: public_ip_lookup
      community.general.ipify_facts:

    - name: Create temporary file for k3s install script
      ansible.builtin.tempfile:
        prefix: k3s-install-script-
        suffix: .sh
      register: install_script

    - name: Set permissions for k3s install script
      ansible.builtin.file:
        path: '{{ install_script.path }}'
        mode: '0740'

    - name: Download k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: '{{ install_script.path }}'

    - name: Read first master token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/token
      delegate_to: '{{ first_master_node_name }}'
      delegate_facts: false
      register: first_master_token_slurp

    - name: Execute k3s install script
      vars:
        default_if_ipv4: '{{ ansible_facts[default_if_name].ipv4.address }}'
        public_inet_ipv4: '{{ public_ip_lookup.ansible_facts.ipify_public_ip }}'

        first_master_default_if_name: '{{ hostvars[first_master_node_name].default_if_name }}'
        first_master_server_ip: '{{ hostvars[first_master_node_name].ansible_facts[first_master_default_if_name].ipv4.address }}'
        first_master_token: "{{ first_master_token_slurp['content'] | b64decode | trim }}"
      ansible.builtin.command:
        argv:
          - '{{ install_script.path }}'
          - --server=https://{{ first_master_server_ip }}:6443
          - --token={{ first_master_token | quote }}
          - --flannel-iface={{ default_if_name }}
          - --node-external-ip={{ public_inet_ipv4 }}
          - --node-ip={{ default_if_ipv4 }}
          - --advertise-address={{ default_if_ipv4 }}

    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      register: reboot_required_file
      ansible.builtin.stat: path=/var/run/reboot-required get_md5=no

    - name: Drain current node
      ansible.builtin.command: /usr/local/bin/kubectl drain {{ inventory_hostname }} --force
      when: reboot_required_file.stat.exists or reboot_desired
      delegate_to: '{{ first_master_node_name }}'
      delegate_facts: false
      failed_when: false

    - name: Stop k3s-agent service
      ansible.builtin.systemd:
        name: k3s-agent
        state: stopped
        enabled: false
      when: reboot_required_file.stat.exists or reboot_desired

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: 'Reboot initiated by Ansible due to kernel updates'
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists or reboot_desired

    - name: Execute k3s-killall
      ansible.builtin.command: /usr/local/bin/k3s-killall.sh
      when: reboot_required_file.stat.exists or reboot_desired

    - name: Start k3s service
      ansible.builtin.systemd:
        name: k3s-agent
        state: started
        enabled: true
      when: reboot_required_file.stat.exists or reboot_desired

    - name: Uncordon current node
      until: uncordon.rc == 0
      register: uncordon
      delay: 5
      delegate_to: '{{ first_master_node_name }}'
      delegate_facts: false
      ansible.builtin.command: /usr/local/bin/kubectl uncordon {{ inventory_hostname }}
      when: reboot_required_file.stat.exists or reboot_desired
