---
- name: Drain current node
  ansible.builtin.command: '/usr/local/bin/kubectl drain {{ inventory_hostname }} --force'
  delegate_to: '{{ node_drain_delegate_host }}'
  delegate_facts: false
  failed_when: false

- name: 'Stop {{ unit_name }} service'
  ansible.builtin.systemd:
    name: '{{ unit_name }}'
    state: stopped
    enabled: false

- name: Reboot the server
  ansible.builtin.reboot:
    msg: 'Reboot initiated by Ansible due to kernel updates'
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: Execute k3s-killall
  ansible.builtin.command: /usr/local/bin/k3s-killall.sh

- name: 'Start {{ unit_name }} service'
  ansible.builtin.systemd:
    name: '{{ unit_name }}'
    state: restarted
    enabled: true

- name: Uncordon current node
  until: uncordon.rc == 0
  register: uncordon
  delay: 5
  delegate_to: '{{ node_drain_delegate_host }}'
  delegate_facts: false
  ansible.builtin.command: /usr/local/bin/kubectl uncordon {{ inventory_hostname }}
